const hoursFromNow = (hours: number) => new Date(Date.now() + hours * 60 * 60 * 1000).toISOString()
const daysFromNow = (days: number) => new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString()

export const MOCK_USER = {
  id: 'mock-user-id',
  email: 'admin@amal.org',
  full_name: 'Admin Test',
  first_name: 'Admin',
  last_name: 'Test',
  role: 'admin_hopital',
  hopital_id: 'mock-hospital-id',
  region: 'Alger',
}

export const MOCK_STATS = {
  users: {
    total: 1250,
    admins: 45,
    donors: 850,
    available_donors: 320,
    patients: 355,
  },
  requests: {
    total: 124,
    pending: 12,
    partially_fulfilled: 8,
    fulfilled: 104,
  },
  schedules: {
    total: 450,
    upcoming: 24,
    completed: 426,
  },
  hospitals: {
    total: 18,
  },
}

export const MOCK_DONORS = [
  {
    id: 'd-1',
    full_name: 'Ahmed Benali',
    blood_type: 'O+',
    phone: '0555123456',
    last_donation: '2026-03-15',
    wilaya: 'Alger',
    age: 28,
    gender: 'M',
    email: 'ahmed@email.com',
    total_donations: 5,
    address: 'Bab El Oued, Alger',
    occupation: 'Infirmier',
    weight_kg: 76,
    preferred_contact: 'Téléphone',
    availability: 'Lun - Jeu, 08:00 - 16:00',
    last_screening: '2026-02-02',
    notes: 'Donneur fiable, accepte les appels d’urgence en journée.',
    emergency_contact_name: 'Nadia Benali',
    emergency_contact_phone: '0555001122',
  },
  {
    id: 'd-2',
    full_name: 'Sara Mansouri',
    blood_type: 'A-',
    phone: '0555987654',
    last_donation: '2026-01-20',
    wilaya: 'Oran',
    age: 34,
    gender: 'F',
    email: 'sara@email.com',
    total_donations: 8,
    address: 'Bir El Djir, Oran',
    occupation: 'Pharmacienne',
    weight_kg: 63,
    preferred_contact: 'Email',
    availability: 'Mar - Sam, 10:00 - 18:00',
    last_screening: '2026-01-10',
    notes: 'Très bon historique, profil rare pour les demandes A-.',
    emergency_contact_name: 'Mourad Mansouri',
    emergency_contact_phone: '0566018899',
  },
  {
    id: 'd-3',
    full_name: 'Yacine Brahimi',
    blood_type: 'B+',
    phone: '0555667788',
    last_donation: '2026-04-02',
    wilaya: 'Sétif',
    age: 22,
    gender: 'M',
    email: 'yacine@email.com',
    total_donations: 2,
    address: 'Ain El Fouara, Sétif',
    occupation: 'Étudiant',
    weight_kg: 71,
    preferred_contact: 'Téléphone',
    availability: 'Tous les jours après 14:00',
    last_screening: '2026-03-30',
    notes: 'Peut être mobilisé rapidement pour des rendez-vous replanifiés.',
    emergency_contact_name: 'Lina Brahimi',
    emergency_contact_phone: '0555448877',
  },
  {
    id: 'd-4',
    full_name: 'Lina Kassim',
    blood_type: 'O-',
    phone: '0555112233',
    last_donation: '2025-11-12',
    wilaya: 'Alger',
    age: 29,
    gender: 'F',
    email: 'lina@email.com',
    total_donations: 4,
    address: 'Hydra, Alger',
    occupation: 'Ingénieure biomédicale',
    weight_kg: 58,
    preferred_contact: 'Téléphone',
    availability: 'Mer - Ven, 09:00 - 15:00',
    last_screening: '2026-01-25',
    notes: 'Donneuse prioritaire pour les urgences O-.',
    emergency_contact_name: 'Karim Kassim',
    emergency_contact_phone: '0555332211',
  },
  {
    id: 'd-5',
    full_name: 'Mourad Slimani',
    blood_type: 'AB+',
    phone: '0555445566',
    last_donation: '2026-05-10',
    wilaya: 'Alger',
    age: 41,
    gender: 'M',
    email: 'mourad@email.com',
    total_donations: 12,
    address: 'Kouba, Alger',
    occupation: 'Gestionnaire',
    weight_kg: 82,
    preferred_contact: 'Téléphone',
    availability: 'Lun - Ven, 07:00 - 13:00',
    last_screening: '2026-05-01',
    notes: 'Très expérimenté, demande un délai de confirmation avant déplacement.',
    emergency_contact_name: 'Amel Slimani',
    emergency_contact_phone: '0555445544',
  },
  {
    id: 'd-6',
    full_name: 'Nora Bensaid',
    blood_type: 'B-',
    phone: '0566778899',
    last_donation: '2026-02-08',
    wilaya: 'Blida',
    age: 31,
    gender: 'F',
    email: 'nora@email.com',
    total_donations: 6,
    address: 'Centre-ville, Blida',
    occupation: 'Enseignante',
    weight_kg: 61,
    preferred_contact: 'Email',
    availability: 'Lun - Ven, après 17:00',
    last_screening: '2026-02-01',
    notes: 'Disponible surtout en soirée, bon profil pour les créneaux de rattrapage.',
    emergency_contact_name: 'Hakim Bensaid',
    emergency_contact_phone: '0566778800',
  },
  {
    id: 'd-7',
    full_name: 'Samir Ouali',
    blood_type: 'A+',
    phone: '0566002211',
    last_donation: '2026-03-01',
    wilaya: 'Boumerdès',
    age: 37,
    gender: 'M',
    email: 'samir@email.com',
    total_donations: 9,
    address: 'Corso, Boumerdès',
    occupation: 'Technicien',
    weight_kg: 79,
    preferred_contact: 'Téléphone',
    availability: 'Mar - Jeu, 08:00 - 12:00',
    last_screening: '2026-02-27',
    notes: 'Historique stable, utile pour les demandes planifiées à l’avance.',
    emergency_contact_name: 'Sonia Ouali',
    emergency_contact_phone: '0566002299',
  },
  {
    id: 'd-8',
    full_name: 'Imane Charef',
    blood_type: 'O+',
    phone: '0557114400',
    last_donation: '2026-04-26',
    wilaya: 'Tipaza',
    age: 26,
    gender: 'F',
    email: 'imane@email.com',
    total_donations: 3,
    address: 'Cherchell, Tipaza',
    occupation: 'Assistante de laboratoire',
    weight_kg: 60,
    preferred_contact: 'Téléphone',
    availability: 'Week-end et jours fériés',
    last_screening: '2026-04-20',
    notes: 'Répond rapidement pour les créneaux week-end.',
    emergency_contact_name: 'Walid Charef',
    emergency_contact_phone: '0557114499',
  },
]

export const MOCK_REQUESTS = [
  {
    id: 'req-1',
    status: 'active',
    blood_type: 'O+',
    urgency_level: 'critical',
    severity: 'critical',
    required_units: 3,
    units_needed: 3,
    donors_confirmed: 1,
    patient_id: 'p-1',
    patient_name: 'Mohamed Brahimi',
    hopital_id: 'mock-hospital-id',
    hospital_name: 'CHU Mustapha Pacha',
    department: 'Bloc opératoire',
    room: 'Salle B12',
    procedure: 'Chirurgie digestive lourde',
    attending_physician: 'Dr. Kaci',
    requested_by: 'Service anesthésie',
    required_by: hoursFromNow(5),
    contact_phone: '021 73 45 20',
    notes: 'Patient instable. Réserve sécurisée requise avant transfert au bloc.',
    created_at: hoursFromNow(-2),
  },
  {
    id: 'req-2',
    status: 'active',
    blood_type: 'A-',
    urgency_level: 'high',
    severity: 'high',
    required_units: 2,
    units_needed: 2,
    donors_confirmed: 0,
    patient_id: 'p-2',
    patient_name: 'Fatima Zohra',
    hopital_id: 'mock-hospital-id',
    hospital_name: 'CHU Mustapha Pacha',
    department: 'Maternité',
    room: 'M04',
    procedure: 'Hémorragie post-partum',
    attending_physician: 'Dr. Haddad',
    requested_by: 'Garde obstétrique',
    required_by: hoursFromNow(3),
    contact_phone: '021 73 48 20',
    notes: 'Recherche donneuses compatibles en priorité.',
    created_at: hoursFromNow(-5),
  },
  {
    id: 'req-3',
    status: 'partially_fulfilled',
    blood_type: 'B+',
    urgency_level: 'medium',
    severity: 'normal',
    required_units: 5,
    units_needed: 2,
    donors_confirmed: 3,
    patient_id: 'p-3',
    patient_name: 'Amine Kasmi',
    hopital_id: 'mock-hospital-id',
    hospital_name: 'CHU Mustapha Pacha',
    department: 'Oncologie',
    room: 'ONC-07',
    procedure: 'Programme transfusionnel',
    attending_physician: 'Pr. Djerbi',
    requested_by: 'Coordinateur hôpital de jour',
    required_by: daysFromNow(2),
    contact_phone: '021 73 11 11',
    notes: 'Demande planifiée, peut être répartie sur deux créneaux.',
    created_at: hoursFromNow(-12),
  },
  {
    id: 'req-4',
    status: 'fulfilled',
    blood_type: 'O-',
    urgency_level: 'critical',
    severity: 'critical',
    required_units: 1,
    units_needed: 0,
    donors_confirmed: 1,
    patient_id: 'p-4',
    patient_name: 'Karima Benali',
    hopital_id: 'mock-hospital-id',
    hospital_name: 'CHU Mustapha Pacha',
    department: 'Urgences',
    room: 'U-03',
    procedure: 'Traumatisme',
    attending_physician: 'Dr. Aouadi',
    requested_by: 'Réanimation',
    required_by: hoursFromNow(-18),
    contact_phone: '021 73 21 98',
    notes: 'Dossier clos après validation du laboratoire.',
    created_at: daysFromNow(-1),
  },
  {
    id: 'req-5',
    status: 'active',
    blood_type: 'AB+',
    urgency_level: 'medium',
    severity: 'normal',
    required_units: 2,
    units_needed: 2,
    donors_confirmed: 1,
    patient_id: 'p-5',
    patient_name: 'Salim Mehdi',
    hopital_id: 'mock-hospital-id',
    hospital_name: 'CHU Mustapha Pacha',
    department: 'Cardiologie',
    room: 'CAR-14',
    procedure: 'Angioplastie programmée',
    attending_physician: 'Dr. Ziani',
    requested_by: 'Cardiologie interventionnelle',
    required_by: daysFromNow(1),
    contact_phone: '021 73 56 90',
    notes: 'Prévoir une marge de sécurité avant intervention du matin.',
    created_at: hoursFromNow(-9),
  },
  {
    id: 'req-6',
    status: 'partially_fulfilled',
    blood_type: 'B-',
    urgency_level: 'high',
    severity: 'high',
    required_units: 4,
    units_needed: 1,
    donors_confirmed: 2,
    patient_id: 'p-6',
    patient_name: 'Leila Ferhat',
    hopital_id: 'mock-hospital-id',
    hospital_name: 'CHU Mustapha Pacha',
    department: 'Hématologie',
    room: 'HEM-02',
    procedure: 'Aplasie médullaire',
    attending_physician: 'Pr. Messaoudi',
    requested_by: 'Unité de greffe',
    required_by: daysFromNow(3),
    contact_phone: '021 73 66 90',
    notes: 'Dernière poche à confirmer avant fin de semaine.',
    created_at: daysFromNow(-2),
  },
  {
    id: 'req-7',
    status: 'cancelled',
    blood_type: 'A+',
    urgency_level: 'medium',
    severity: 'normal',
    required_units: 1,
    units_needed: 0,
    donors_confirmed: 0,
    patient_id: 'p-7',
    patient_name: 'Yasmine Driouech',
    hopital_id: 'mock-hospital-id',
    hospital_name: 'CHU Mustapha Pacha',
    department: 'Pédiatrie',
    room: 'PED-09',
    procedure: 'Anémie aiguë',
    attending_physician: 'Dr. Hamri',
    requested_by: 'Pédiatrie de garde',
    required_by: daysFromNow(-1),
    contact_phone: '021 73 90 11',
    notes: 'Demande annulée après réévaluation clinique.',
    created_at: daysFromNow(-4),
  },
  {
    id: 'req-8',
    status: 'active',
    blood_type: 'O+',
    urgency_level: 'high',
    severity: 'high',
    required_units: 3,
    units_needed: 3,
    donors_confirmed: 0,
    patient_id: 'p-8',
    patient_name: 'Nassim Ait Ali',
    hopital_id: 'mock-hospital-id',
    hospital_name: 'CHU Mustapha Pacha',
    department: 'Neurochirurgie',
    room: 'NCH-05',
    procedure: 'Craniotomie urgente',
    attending_physician: 'Dr. Ferroukhi',
    requested_by: 'Bloc neuro',
    required_by: hoursFromNow(8),
    contact_phone: '021 73 42 65',
    notes: 'Besoin confirmé avant prise en charge au bloc demain matin.',
    created_at: hoursFromNow(-7),
  },
]

export const MOCK_APPOINTMENTS = [
  {
    id: 'app-1',
    donor_id: 'd-1',
    donor_name: 'Ahmed Benali',
    blood_type: 'O+',
    scheduled_time: hoursFromNow(1),
    status: 'scheduled',
    units_expected: 2,
    room: 'Salle collecte 1',
    assigned_nurse: 'Nurse Samia',
    notes: 'Confirmer la disponibilité 30 minutes avant.',
    request_id: 'req-1',
  },
  {
    id: 'app-2',
    donor_id: 'd-3',
    donor_name: 'Yacine Brahimi',
    blood_type: 'B+',
    scheduled_time: hoursFromNow(4),
    status: 'scheduled',
    units_expected: 1,
    room: 'Salle collecte 2',
    assigned_nurse: 'Nurse Nabil',
    notes: 'Transport déjà confirmé.',
    request_id: 'req-3',
  },
  {
    id: 'app-3',
    donor_id: 'd-5',
    donor_name: 'Mourad Slimani',
    blood_type: 'AB+',
    scheduled_time: daysFromNow(1),
    status: 'scheduled',
    units_expected: 1,
    room: 'Salle collecte 1',
    assigned_nurse: 'Nurse Assia',
    notes: 'Préférer le créneau du matin.',
    request_id: 'req-5',
  },
  {
    id: 'app-4',
    donor_id: 'd-2',
    donor_name: 'Sara Mansouri',
    blood_type: 'A-',
    scheduled_time: daysFromNow(-1),
    status: 'completed',
    units_expected: 1,
    units_donated: 1,
    room: 'Salle collecte 3',
    assigned_nurse: 'Nurse Yasmine',
    notes: 'Don effectué sans incident.',
    request_id: 'req-2',
  },
  {
    id: 'app-5',
    donor_id: 'd-6',
    donor_name: 'Nora Bensaid',
    blood_type: 'B-',
    scheduled_time: daysFromNow(2),
    status: 'scheduled',
    units_expected: 2,
    room: 'Salle collecte 2',
    assigned_nurse: 'Nurse Mourad',
    notes: 'Coordination avec le service d’hématologie.',
    request_id: 'req-6',
  },
  {
    id: 'app-6',
    donor_id: 'd-7',
    donor_name: 'Samir Ouali',
    blood_type: 'A+',
    scheduled_time: daysFromNow(-2),
    status: 'cancelled',
    units_expected: 1,
    room: 'Salle collecte 1',
    assigned_nurse: 'Nurse Ines',
    notes: 'Annulé par indisponibilité du donneur.',
    request_id: 'req-7',
  },
  {
    id: 'app-7',
    donor_id: 'd-8',
    donor_name: 'Imane Charef',
    blood_type: 'O+',
    scheduled_time: daysFromNow(3),
    status: 'rescheduled',
    units_expected: 1,
    room: 'Salle collecte 4',
    assigned_nurse: 'Nurse Lila',
    notes: 'Décalé au week-end à la demande du donneur.',
    request_id: 'req-8',
  },
  {
    id: 'app-8',
    donor_id: 'd-4',
    donor_name: 'Lina Kassim',
    blood_type: 'O-',
    scheduled_time: hoursFromNow(6),
    status: 'scheduled',
    units_expected: 1,
    room: 'Salle collecte 1',
    assigned_nurse: 'Nurse Samia',
    notes: 'Créneau prioritaire pour demande critique.',
    request_id: 'req-1',
  },
]

export const MOCK_TEAM_MEMBERS = [
  {
    id: 'tm-1',
    first_name: 'Samia',
    last_name: 'Khelifi',
    role: 'Coordinatrice de collecte',
    department: 'Banque du sang',
    email: 'samia.khelifi@amal.dz',
    phone: '021734001',
    status: 'active',
    shift: '06:00 - 14:00',
  },
  {
    id: 'tm-2',
    first_name: 'Nabil',
    last_name: 'Saadi',
    role: 'Infirmier référent',
    department: 'Salle collecte 2',
    email: 'nabil.saadi@amal.dz',
    phone: '021734002',
    status: 'active',
    shift: '08:00 - 16:00',
  },
  {
    id: 'tm-3',
    first_name: 'Yasmine',
    last_name: 'Ferhat',
    role: 'Technicienne laboratoire',
    department: 'Immuno-hématologie',
    email: 'yasmine.ferhat@amal.dz',
    phone: '021734003',
    status: 'active',
    shift: '07:00 - 15:00',
  },
  {
    id: 'tm-4',
    first_name: 'Ines',
    last_name: 'Hadj',
    role: 'Cadre administratif',
    department: 'Admissions dons',
    email: 'ines.hadj@amal.dz',
    phone: '021734004',
    status: 'pending',
    shift: '09:00 - 17:00',
  },
]

export const MOCK_HOSPITALS = [
  { id: 'mock-hospital-id', name: 'CHU Mustapha Pacha', region: 'Alger', address: 'Place du 1er Mai' },
  { id: 'h-2', name: 'EPH Bologhine', region: 'Alger', address: 'Bologhine' },
  { id: 'h-3', name: 'CHU 1er Novembre', region: 'Oran', address: 'Bir El Djir' },
  {
    id: 'h-univ-algiers',
    name: 'University Hospital of Algiers (Université d\'Alger)',
    region: 'Alger',
    address: "Université d'Alger campus",
    latitude: 35.6911,
    longitude: -0.6417
  },
]

export const MOCK_RESPONSES: Record<string, any> = {
  '/api/auth/login': { access_token: 'mock-token', token_type: 'bearer' },
  '/api/auth/me': MOCK_USER,
  '/api/admin/dashboard': MOCK_STATS,
  '/api/admin/requests': MOCK_REQUESTS,
  '/api/admin/hospitals': MOCK_HOSPITALS,
  '/api/admin/force-match': { data: 5 },
  '/api/auth/profile': MOCK_USER,
  '/api/admin/appointments': MOCK_APPOINTMENTS,
  '/api/admin/donors': MOCK_DONORS,
  '/api/admin/team': MOCK_TEAM_MEMBERS,
}
